[project]
name = "homework5"
version = "0.1.0"
description = "Homework5 by Soumen S"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.120.1",
    "jupyter>=1.1.1",
    "requests>=2.32.5",
    "scikit-learn==1.6.1",
    "uvicorn>=0.38.0",
]
